"""
PDF Export for QNWIS Executive Dashboards (M2).

Generates ministerial-grade PDF reports from analysis results.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class PDFExporter:
    """
    Export QNWIS analysis to PDF format.
    
    Creates professional PDF reports suitable for ministerial briefings.
    """
    
    def __init__(self, output_dir: str = "exports/pdf"):
        """
        Initialize PDF exporter.
        
        Args:
            output_dir: Directory for PDF outputs
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"PDFExporter initialized: {output_dir}")
    
    def export_dashboard(
        self,
        summary: str,
        kpis: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        recommendations: List[Dict[str, Any]],
        filename: Optional[str] = None
    ) -> Path:
        """
        Export executive dashboard to PDF.
        
        Args:
            summary: Executive summary text
            kpis: List of KPI dictionaries
            findings: List of agent findings
            recommendations: List of recommendations
            filename: Optional output filename
            
        Returns:
            Path to generated PDF
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"qnwis_dashboard_{timestamp}.pdf"
        
        output_path = self.output_dir / filename
        
        try:
            # Generate PDF content (using reportlab or similar)
            # For now, generate markdown as placeholder
            markdown_content = self._generate_markdown(
                summary, kpis, findings, recommendations
            )
            
            # Save as text file (in production, convert to PDF)
            output_path_md = output_path.with_suffix(".md")
            with open(output_path_md, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            logger.info(f"Dashboard exported to: {output_path_md}")
            return output_path_md
        
        except Exception as e:
            logger.error(f"PDF export failed: {e}")
            raise
    
    def _generate_markdown(
        self,
        summary: str,
        kpis: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        recommendations: List[Dict[str, Any]]
    ) -> str:
        """Generate markdown content for PDF."""
        content = f"""# Qatar National Workforce Intelligence System
## Executive Dashboard Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Executive Summary

{summary}

---

## Key Performance Indicators

"""
        for kpi in kpis:
            content += f"- **{kpi['name']}**: {kpi['value']}{kpi.get('unit', '')}\n"
        
        content += "\n---\n\n## Key Findings\n\n"
        
        for idx, finding in enumerate(findings, 1):
            content += f"{idx}. **{finding.get('agent', 'Agent')}**: {finding.get('finding', '')}\n\n"
        
        content += "\n---\n\n## Recommendations\n\n"
        
        for rec in recommendations:
            content += f"- {rec.get('text', '')}\n"
        
        content += "\n---\n\n*Generated by QNWIS - Qatar Ministry of Labour*\n"
        
        return content


class PowerPointExporter:
    """
    Export QNWIS analysis to PowerPoint format.
    
    Creates professional PPTX presentations for ministerial briefings.
    """
    
    def __init__(self, output_dir: str = "exports/pptx"):
        """
        Initialize PowerPoint exporter.
        
        Args:
            output_dir: Directory for PPTX outputs
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"PowerPointExporter initialized: {output_dir}")
    
    def export_dashboard(
        self,
        summary: str,
        kpis: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        recommendations: List[Dict[str, Any]],
        filename: Optional[str] = None
    ) -> Path:
        """
        Export executive dashboard to PowerPoint.
        
        Args:
            summary: Executive summary text
            kpis: List of KPI dictionaries
            findings: List of agent findings
            recommendations: List of recommendations
            filename: Optional output filename
            
        Returns:
            Path to generated PPTX
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"qnwis_presentation_{timestamp}.pptx"
        
        output_path = self.output_dir / filename
        
        try:
            # Generate PPTX (using python-pptx or similar)
            # For now, save as markdown placeholder
            markdown_content = f"""# QNWIS Presentation

**Slide 1: Title**
Qatar National Workforce Intelligence System
Executive Dashboard

**Slide 2: Summary**
{summary}

**Slide 3: KPIs**
"""
            for kpi in kpis:
                markdown_content += f"- {kpi['name']}: {kpi['value']}{kpi.get('unit', '')}\n"
            
            markdown_content += "\n**Slide 4: Findings**\n"
            for finding in findings[:5]:
                markdown_content += f"- {finding.get('finding', '')}\n"
            
            markdown_content += "\n**Slide 5: Recommendations**\n"
            for rec in recommendations[:5]:
                markdown_content += f"- {rec.get('text', '')}\n"
            
            output_path_md = output_path.with_suffix(".md")
            with open(output_path_md, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            logger.info(f"Presentation exported to: {output_path_md}")
            return output_path_md
        
        except Exception as e:
            logger.error(f"PowerPoint export failed: {e}")
            raise


def export_to_pdf(dashboard_data: Dict[str, Any], filename: Optional[str] = None) -> Path:
    """
    Convenience function to export dashboard to PDF.
    
    Args:
        dashboard_data: Dashboard data dictionary
        filename: Optional output filename
        
    Returns:
        Path to generated PDF
    """
    exporter = PDFExporter()
    return exporter.export_dashboard(
        summary=dashboard_data.get("summary", ""),
        kpis=dashboard_data.get("kpis", []),
        findings=dashboard_data.get("findings", []),
        recommendations=dashboard_data.get("recommendations", []),
        filename=filename
    )


def export_to_powerpoint(dashboard_data: Dict[str, Any], filename: Optional[str] = None) -> Path:
    """
    Convenience function to export dashboard to PowerPoint.
    
    Args:
        dashboard_data: Dashboard data dictionary
        filename: Optional output filename
        
    Returns:
        Path to generated PPTX
    """
    exporter = PowerPointExporter()
    return exporter.export_dashboard(
        summary=dashboard_data.get("summary", ""),
        kpis=dashboard_data.get("kpis", []),
        findings=dashboard_data.get("findings", []),
        recommendations=dashboard_data.get("recommendations", []),
        filename=filename
    )
