"""Test parallel scenario execution on GPUs 0-5 with fact verification."""

import requests
import json
import time

API_URL = "http://localhost:8000/api/v1/council/stream"

# Complex strategic query - should trigger parallel scenarios
query = "Should Qatar invest $50B in a financial hub or logistics hub? Analyze job creation potential."

print("STEP 4: PARALLEL SCENARIOS TEST")
print("="*80)
print(f"Query: {query}")
print("\nExpected behavior:")
print("  - Classified as COMPLEX")
print("  - 6 scenarios generated by Claude Sonnet 4")
print("  - Each scenario runs full 12-agent workflow")
print("  - Parallel execution on GPUs 0-5")
print("  - Meta-synthesis across scenarios")
print("  - Fact verification on GPU 6")
print("  - Target time: ~40-50s (parallel speedup)")
print("="*80)
print("Submitting query...")
print("="*80)

start_time = time.time()

try:
    response = requests.post(
        API_URL,
        json={"question": query},
        headers={"Content-Type": "application/json"},
        stream=True,
        timeout=1800  # 30 minutes max
    )
    
    if response.status_code != 200:
        print(f"ERROR: HTTP {response.status_code}")
        print(response.text)
        exit(1)
    
    stages_seen = []
    events = []
    scenario_count = 0
    parallel_exec_found = False
    meta_synthesis_found = False
    
    for line in response.iter_lines():
        if line:
            line = line.decode('utf-8')
            if line.startswith('data: '):
                data = line[6:]
                try:
                    event = json.loads(data)
                    events.append(event)
                    
                    stage = event.get('stage', '')
                    status = event.get('status', '')
                    payload = event.get('payload', {})
                    
                    # Track scenarios
                    if 'scenario' in stage.lower():
                        if 'scenarios' in payload:
                            scenario_count = len(payload.get('scenarios', []))
                            print(f"\n[INFO] {scenario_count} scenarios generated!")
                        if 'parallel' in stage.lower():
                            parallel_exec_found = True
                        if 'meta' in stage.lower():
                            meta_synthesis_found = True
                    
                    if stage and stage not in stages_seen:
                        stages_seen.append(stage)
                        print(f"[{len(stages_seen):2}] {stage:25} {status}")
                    
                except json.JSONDecodeError:
                    pass
    
    elapsed = time.time() - start_time
    
    print("\n" + "="*80)
    print("RESULTS")
    print("="*80)
    print(f"Execution time: {elapsed:.1f}s ({elapsed/60:.1f} minutes)")
    print(f"Total stages: {len(stages_seen)}")
    print(f"Scenarios generated: {scenario_count}")
    print(f"Parallel execution: {parallel_exec_found}")
    print(f"Meta-synthesis: {meta_synthesis_found}")
    
    print(f"\nStages: {stages_seen}")
    
    # Check for parallel scenario indicators
    has_scenario_gen = 'scenario_gen' in stages_seen
    has_parallel_exec = parallel_exec_found or any('parallel' in s.lower() for s in stages_seen)
    has_meta_synthesis = meta_synthesis_found or any('meta' in s.lower() for s in stages_seen)
    
    print(f"\nParallel Scenario Indicators:")
    print(f"  Scenario generation: {has_scenario_gen}")
    print(f"  Parallel execution: {has_parallel_exec}")
    print(f"  Meta-synthesis: {has_meta_synthesis}")
    
    if scenario_count >= 4:
        print(f"\n[PASS] Generated {scenario_count} scenarios (target: 4-6)")
    
    if has_parallel_exec:
        print(f"[PASS] Parallel execution detected!")
    
    if has_meta_synthesis:
        print(f"[PASS] Meta-synthesis across scenarios!")
    
    # Check verification
    if 'verify' in stages_seen:
        print(f"[PASS] GPU fact verification executed!")
        
        verify_events = [e for e in events if e.get('stage') == 'verify']
        if verify_events:
            verify_payload = verify_events[-1].get('payload', {})
            fact_check = verify_payload.get('fact_check_results', {})
            gpu_verification = fact_check.get('gpu_verification')
            
            if gpu_verification:
                print(f"\nGPU Fact Verification:")
                print(f"  Total claims: {gpu_verification.get('total_claims', 0)}")
                print(f"  Verified claims: {gpu_verification.get('verified_claims', 0)}")
                print(f"  Rate: {gpu_verification.get('verification_rate', 0):.0%}")
    
    print("\n" + "="*80)
    if scenario_count >= 4 or elapsed < 120:
        print(f"[SUCCESS] STEP 4 PASSED - Parallel scenarios working!")
        print(f"  Execution time: {elapsed:.1f}s")
        if elapsed < 120:
            print(f"  Performance: EXCELLENT (< 2 minutes)")
    else:
        print(f"[INFO] System completed but check scenario generation")
    print("="*80)
    
except Exception as e:
    print(f"ERROR: {e}")
    import traceback
    traceback.print_exc()
    exit(1)

